# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Graphical Algebra
description: >-
  A resource to explain, discover, and expand on Graphical Algebra.
url: "https://nadrieril.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/graphical-algebra" # the subpath of your site, e.g. /blog

# email: your-email@example.com
github_username:  Nadrieril
# twitter_username: jekyllrb

header_pages:
  - "archive.md"

# Theme and plugins
theme: minima
plugins:
  - jektex
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-twitter-plugin
  - jekyll-youtube

optional_front_matter:
  remove_originals: true

readme_index:
  enabled: true
  remove_originals: true
  with_frontmatter: true

titles_from_headings:
  strip_title: true
  collections: true

# Exclude from processing.
exclude:
  - .envrc
  - .github
  - .gitignore
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - Makefile
  - nix
  - shell.nix
  - vendor
