# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Graphical Algebra
description: >-
  A resource to explain, discover, and expand on Graphical Algebra.
url: "https://nadrieril.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/graphical-algebra" # the subpath of your site, e.g. /blog

# email: your-email@example.com
github_username:  Nadrieril
# twitter_username: jekyllrb

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .envrc
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - Makefile
  - nix
  - README.md
  - shell.nix
